### PR TITLE
allow `setSigma` to be generic over the graph typ

### LINKED ISSUE #58: `ref` is not generic
## `ref` is not generic

`ref` is not generic. This causes a mismatch between `ref={setSigma}` and the actual type of `setSigma`.

We give it `setSigma`: `React.Dispatch<React.SetStateAction<Sigma<MyGraph> | null>>` 

but the `ref` enforces `setSigma`: `React.Dispatch<React.SetStateAction<Sigma<AbstractGraph<Attributes, Attributes, Attributes>> | null>>` 

**React-sigma-v2:**  3.4.2
**Sigma.js version:** 2.4.0
**Graphology version:** 0.25.4
**Operating System:** LG Laundry machine OS
**Web browser:** Edge 120.0.0

### Steps to reproduce

Check the live example https://codesandbox.io/p/sandbox/react-sigma-example-forked-9mks58?file=%2Fsrc/App.tsx

### Expected behavior

I can use `setSigma` with custom graph type so I can get better intellisense

### Actual behavior

Computer says no:

image

## Note

If the issue has an inactivity of **30 days**, it becomes stale.
With an additional inactivity of **14 days**, the issue is closed

### PR DESCRIPTION
**Pull request by kristof-mattei**
Closes #58

### CODE REVIEW

**Comment by sim51** [comment]
Thanks for the PR will check that.

BTW, I'm waiting the release of sigma v3 to make a refacto of this library. 
The v3 comes with more generic types (check https://github.com/jacomyal/sigma.js/issues/1359), and I need to handle that also in this lib.

**Comment by kristof-mattei** [comment]
> Thanks for the PR will check that.
> 
> BTW, I'm waiting the release of sigma v3 to make a refacto of this library. The v3 comes with more generic types (check [jacomyal/sigma.js#1359](https://github.com/jacomyal/sigma.js/issues/1359)), and I need to handle that also in this lib.

You want me to try merge that one in and see how it works?

**Comment by sim51** [comment]
It's merged

**Comment by sim51** [comment]
> You want me to try merge that one in and see how it works?

Thanks a lot, but I will do it. With the next version of sigma, I will do a major release, so  I will take advantage of it to make some cleanups and breaking changes.

**Pull request closed without merging**
